#!/bin/bash

echo "🔥 Firebase Cloud Messaging Setup"
echo "=================================="
echo ""
echo "📋 Steps to complete:"
echo ""
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Create project: HeartLink"
echo "3. Add Android app with package: com.heartlink.app"
echo "4. Download google-services.json"
echo "5. Place it in: flutter_app/android/app/google-services.json"
echo ""
echo "6. Get Server Key:"
echo "   - Project Settings → Cloud Messaging"
echo "   - Copy 'Server key'"
echo "   - Add to .env: FCM_SERVER_KEY=your_key_here"
echo ""
echo "7. Run: cd flutter_app && flutter pub get"
echo ""
echo "✅ Files already created:"
echo "   - lib/services/fcm_service.dart"
echo "   - services/fcm_notification_service.py"
echo "   - routes/fcm.py"
echo ""
echo "📱 Notification Types:"
echo "   ✓ Match notifications"
echo "   ✓ New message alerts"
echo "   ✓ Like received"
echo "   ✓ Profile views"
echo ""
echo "💰 Cost: $0 (FREE Forever)"
echo ""
